### PR TITLE
Adding shell and create-home to useradd command

### PR DESCRIPTION
**Pull request by FutureSharks**
It's a bit annoying having a user without a home directory and a normal shell.

### CODE REVIEW

**Comment by FutureSharks** [comment]
When I log in I get this error message on Ubuntu:

```
$ ssh my.user@52.208.162.66
Keymaker: Your user account has been replicated onto this host, but SSH will not recognize it until you reconnect.
Keymaker: Connect again to log in to your account.
/usr/local/bin/keymaker-create-account-for-iam-user failed: exit code 75

/usr/local/bin/keymaker-create-account-for-iam-user failed: exit code 77

/usr/local/bin/keymaker-create-account-for-iam-user failed: exit code 77

Permission denied (publickey,keyboard-interactive).
```

But then after, my account is created with home directory and a proper shell set. Is that normal?

**Comment by FutureSharks** [comment]
FYI I've only tested on Ubuntu 16.04/

**Comment by kislyuk** [comment]
Thanks for the PR.

I think both these changes should be configurable at hook install time. Also, this does need to be tested on Red Hat (I don't have one handy).

**Comment by FutureSharks** [comment]
It's pretty unconventional to have a user with no shell and no home
directory. Wouldn't it make sense to merge this now and then add install
options feature in a separate PR later?

I'll test on RHEL with docker later to make sure syntax is the same.

**Comment by kislyuk** [comment]
I thought the shell defaults to /bin/sh. Certainly I don't end up with no shell when I use keymaker with Ubuntu. (Come to think of it, I think it might also be creating a home directory for me as well... I'm not sure what's going on to cause your system to behave otherwise.)

**Comment by FutureSharks** [comment]
Interesting. I'll retest and get back to you.

**Comment by FutureSharks** [comment]
On my instances running Ubuntu 16.04 this problem exists. You can also see it quickly using docker, no shell and no home dir:
```
$ docker run -it ubuntu:16.04 bash -c -- "useradd test1 --comment "test1" --uid 6666; grep test1 /etc/passwd; ls /home/test1"
test1:x:6666:6666:test1:/home/test1:
ls: cannot access '/home/test1': No such file or directory
```

Same issue for Ubuntu 17. The reason for that most things in `/etc/default/useradd` on Ubuntu are commented out.

On Centos it seems to work OK because `/etc/default/useradd` is configured to add home/shell:
```
$ docker run -it centos:7 bash -c -- "useradd test1 --comment "test1" --uid 6666; grep test1 /etc/passwd; ls /home/test1"
test1:x:6666:6666:test1:/home/test1:/bin/bash
```

**Comment by FutureSharks** [comment]
So on one hand you could say it's not the responsibility of keymaker to fix this and that the admin should update `/etc/default/useradd` accordingly. But on the other hand keymaker is providing simple lightweight user management and a user without a shell/home is pretty useless.

Totally up to you, feel free to close this PR if you wish :simple_smile:

**Comment by kislyuk** [comment]
I don't mind merging this, but can you please test the original PR with centos? I don't have a centos image handy and need to make sure it understands what `--shell "/bin/bash" --create-home` means.

**Comment by FutureSharks** [comment]
Sure thing.

CentOS 7:
```
$ docker run -it centos:7 bash -c -- "useradd test1 --comment "test1" --uid 6666 --shell '/bin/bash' --create-home; grep test1 /etc/passwd; ls -d /home/test1"
test1:x:6666:6666:test1:/home/test1:/bin/bash
/home/test1
```

CentOS 6:
```
$ docker run -it centos:6 bash -c -- "useradd test1 --comment "test1" --uid 6666 --shell '/bin/bash' --create-home; grep test1 /etc/passwd; ls -d /home/test1"
test1:x:6666:6666:test1:/home/test1:/bin/bash
/home/test1
```

Looks good.

**Comment by kislyuk** [comment]
Filed #20 to keep track of shell customization.

**Pull request merged**
